ocf/utils

- bludgeon/bludgeon.py
Puppet installs wp-cli system-wide on login servers, so we can just use that.
See also ocf/puppet@1d9eae87d27283aabbf3959f6b0212fb43096b58 and 596bf1fb33f6cec0914bc670980841737e0cc5e9
> bludgeon: use system-installed wp-cli.phar

- staff/web/bludgeon
Currently running bludgeon as root works great but will create files owned by root in the user's web directory, so you have to chown it afterwards. Instead, we can run it as the user and read their password out of wp-config.php.
Potentially users could run this too, but I doubt they will.
> bludgeon: don't run as root, read pass from config

- sbin/ldap-lint
- staff/sys/ldap-lint
This is actually pretty great. Sample run (with some extra stuff removed since we have lots of issues):
```
[tornado] ldap ip 169.229.10.90 doesn't match dns ip 169.229.226.90
[limniceruption] has unrecognized puppetVar: production=169.229.10.204
[ragnarok] ldap ip 169.229.10.203 doesn't match dns ip 169.229.226.255
[ragnarok] bad reverse DNS for 169.229.10.203: solarflare.OCF.Berkeley.EDU.
[hozer-40] has no A record in DNS
[hozer-40] bad reverse DNS for 169.229.10.40: dev-sandstorm.OCF.Berkeley.EDU.
[hozer-41] has no A record in DNS
[hozer-41] bad reverse DNS for 169.229.10.41: earthquake.OCF.Berkeley.EDU.
[solarflare] has same IP address as ragnarok
```
(It finds 154 errors but most of these are due to the IP address munging puppet does right now.)
> Add ldap-lint script

- printing/paper
I overheard some people in the lab today who were confused about the print counts listed in the notification. This should make the desktop notifications more specific that the paper counts listed are remaining amounts, not how many pages the user has already printed in the current day or semester.
> Specify paper remaining for desktop notifications

- printing/paper
The new command is functionally equivalent to the old paper script but with a few small changes:
1. The username and the -v flag passed to the script can now be interchanged, so the order does not matter.
2. If the script cannot find a user or the username is formatted badly (not all letters), then the new script will exit with an error code (1) instead of the perl script's exit code of 0.
Otherwise, the main changes apart from the language conversion are that some unused variables have been removed and the history comments in the old perl script have been removed too. The history will stick around in git, so that should be fine.
> Convert paper command to use bash instead of perl

- staff/acct/sorry/sorry
Only sends an email if we have one on file.
Use email footer defined in ocflib constants.
> Notify sorried user by email

- staff/lab/ocf-tv
If ssh is killed during a password prompt, terminal echo is
disabled and needs to be re-enabled. This should not happen
with cleanup after SIGTERM, but just in case, per #32.
Alternatively, we can disable ssh password prompts entirely
with `-o BatchMode=yes` and use Kerberos/GSSAPI.
Personally I prefer that approach to providing my password
to an ocf-tv script, but this is a simple change for now.
> echo stty after ocf-tv connect

- staff/lab/ocf-tv
Previously, when an exception was raised, we would never
send SIGTERM to ssh. ssh would continue to run, stuck in
the password prompt, despite the error traceback.
> Terminate ssh on ocf-tv exception

- staff/lab/ocf-tv
Now you can do `$ ocf-tv volume (0, 150)` to change the volume of the TV from 0% to 150% of baseline. It seems to work pretty decently, occasionally asks for you for a password to tornado. `connect` is still the default. 
When it does ask for a password however, `connect` will timeout if you aren't able to type the pwd fast enough, and after that fails, the terminal begins to exhibit weird behavior - no newlines on enter, no characters shown when typing, although it stills reads the input and executes when you press enter. Need to spawn a new terminal to fix it. Can't really explain why that happens when login fails.
> Add volume control to ocf-tv

- staff/sys/makevm
Since we currently install stretch on new VMs, there should be no trouble merging.
> makevm: use predictable network interface names

- staff/lab/ocf-tv
now you can call `ocf-tv tunnel-audio` and whatever's playing on your local desktop will start playing on the TV, and `ocf-tv stop-tunnel` does what you might expect. Also, `ocf-tv mute` now toggles mute instead of hackishly setting volume to 0.
> ocf-tv features

- staff/sys/migrate-vm
I tested this by moving dev-maelstrom to riptide and then back to jaws. Finally production VMs can be ported over there.
The script now reads the VM's LVM volume from virsh, and lets you specify the destination VG with the `--vg` option.
> migrate-vm: Support volume groups other than 'vg'

- staff/sys/firewall
This modifies the firewall script to use the free NetX JNLP
launcher rather than Oracle's proprietary JRE.
> firewall: use NetX

- .pre-commit-config.yaml
- acct/check
- acct/checkacct
- desktop/pdf-open
- shell-lint.sh
- staff/acct/sorry/sorry
- staff/acct/sorry/unsorry
- staff/mail/build-vhost-mail
- staff/puppet/gen-keytab
- staff/puppet/gen-rootpw
- staff/sys/ldap-add-host
- sys/how
- update-symlinks
A bit messy on the first commit because there was a lot to fix, but `shellcheck` should keep our shell scripts more consistent and less error-prone. I'd like to submit a PR upstream to [pre-commit-shell](https://github.com/detailyang/pre-commit-shell) to support using types, because currently it only supports checking files that end in the correct extension:
files: (\.sh|\.zsh|\.ksh)$
> Add shellcheck pre-commit hook

- staff/meetings/bod
- staff/meetings/bod.py
- staff/meetings/meetings.py
- staff/meetings/minutes
This commit makes the minutes script split the "Attendance"
block in BoD minutes. The note-taker still writes a single
Attendance block, like before; however, after they exit the
text editor, the Attendance block is replaced with two blocks,
an attendance block for directors and an attendance block for
guests. Guests are further marked with an asterisk if they
choose to join BoD at that meeting.
Major changes have been made to the BoD module. Most notably,
the membership file is eliminated. Membership is now dynamically
determined from the attendance lists in the minutes.
One drawback is that you cannot run `minutes` to take BoD minutes
twice in the same day without re-combining the attendance lists,
or else it crashes. This can be remedied in the future.
> Distinguish directors and guests in BoD attendance lists

- staff/sys/makevm
I wondered why all the new VMs on riptide were on `/dev/vg` instead of `/dev/vg-nvme`. Well, now we can start to put them on the fancy drives we paid for!
> makevm: Add option to specify LVM volume group

- staff/sys/ssh-list
Let's not try to SSH into random dhcp-* hosts, or into blackhole, or into riptide-mgmt, or into lb (when we're already SSHing into whatever server lb actually happens to represent)
> ssh-list: restrict filter for all hosts

- makeservices/easywp
A script that an OCF user can run (ideally should be called in response to a registered user clicking a button on the OCF Website) to easily set up WordPress on their account and forgo all command line interaction. The user can finish setting up WordPress in a browser at https://www.ocf.berkeley.edu/~username
> Add setup wordpress script

- acct/check-dns
Here's what it looks like:
```
$ ./check-dns ggroup
Domain                                Type      Value
------------------------------------  --------  ----------------------------------------------------------------------------------------
dev-app.ocf.berkeley.edu              CNAME     werewolves.ocf.berkeley.edu.
dev-dev-app.ocf.berkeley.edu          CNAME     dev-werewolves.ocf.berkeley.edu.
dev-dev-vhost-alias.ocf.berkeley.edu  A         169.229.226.37
dev-dev-vhost-alias.ocf.berkeley.edu  AAAA      2607:f140:8801::1:37
dev-dev-vhost.ocf.berkeley.edu        A         169.229.226.37
dev-dev-vhost.ocf.berkeley.edu        AAAA      2607:f140:8801::1:37
dev-dev-vhost.ocf.berkeley.edu        MX        5 dev-anthrax.ocf.berkeley.edu.
dev-vhost-alias.ocf.berkeley.edu      A …
```
> check-dns: Tabulate output

- staff/sys/makevm
Since we now auto-populate /etc/ssh/ssh_known_hosts via puppet,
when rebuilding a VM, makevm sometimes prints an ugly host key
mismatch warning because the new VM's key doesn't match the cached
one in /etc/ssh/ssh_known_hosts. Fix this problem by ignoring that
file.
> makevm: set GlobalKnownHostsFile=/dev/null

- sbin/last-lab
- staff/lab/last-lab
This command is like (a subset of) the `last` command, except it
prints out logins across desktops, retrieved from the ocfstats
database.
> Add "last for desktops" script

- staff/lab/last-lab
Implements the `-s`, `-t`, and `-p` options from the `last` command (although the semantics of `-s` are slightly different). This will make it easy to:
- List which members are in the lab currently (`last-lab -p now`)
- List which members were in the lab at 10:00 AM today (`last-lab -p 10:00`)
- List which members have used a lab computer since midnight on February 1, 2018 (`last-lab -s 20180201`)
- And more
> last-lab: implement -s, -t, -p

- acct/chsh
- acct/update-email
I originally rewrote `chsh` in bash, but decided rewriting it in python was better to be able to use some ocflib functions and generally be more maintainable.
This depends on the recently merged changes made in https://github.com/ocf/ocflib/pull/148 and in https://github.com/ocf/ocflib/commit/c2c5b9c5f17f139761027d95139209e3f566ee4f.
Testing done:
- `chsh`
- With a valid shell and a valid and invalid kerberos ticket
- With a invalid shell and a valid and invalid kerberos ticket
- `update-email`
- With a invalid email already in my LDAP
- With a valid email already, but no kerberos ticket
- In auto mode with a valid/invalid email
- With entering an invalid email to change to (including trying to change to an OCF email, which isn't allowed)
One thing to mention is that both scripts have a …
> Replace last python2 scripts with python3

- staff/lab/ocf-tv
Currently `ocf-tv mute` gives a python traceback when run. This commit fixes the issue.
> Fix ocf-tv mute

- sbin/gen-kubernetes-cert
- staff/kubernetes/gen-kubernetes-cert
Lets OCF staff authenticate to Kubernetes. See https://kubernetes.io/docs/reference/access-authn-authz/authentication/#input-and-output-formats for more information. Once this is merged, we can actually start to include this in user configs for seamless authentication.
> Add kubernetes credentials auth script

- staff/kubernetes/gen-kubernetes-cert
This avoid problems with ssh kerberos auth. See discussion at https://moffle.fuqu.jp/ocf/%23rebuild/20190303#L107.
Tested and working on supernova.
> gen-kubernetes-cert: choose a specific master to connect to

- .pre-commit-config.yaml
- makeservices/makehttp
- staff/meetings/meetings.py
Committed via https://github.com/asottile/all-repos
> Migrate from autopep8-wrapper to mirrors-autopep8

- staff/sys/ocf-kubernetes-deploy
We need this for the `snmp_exporter` repo lol
> ocf-kubernetes-deploy: replace underscores with dashes in app name

- staff/sys/ocf-kubernetes-deploy
This uses the packaged kubernetes-deploy as in https://github.com/ocf/kubernetes-deploy-deb instead of the given Dockerfile. kubernetes-deploy is in ocf::extrapackages, so it should be installed whenever kubectl is installed.
> Use packaged kubernetes-deploy

- staff/lab/lab-wakeup
Requested by cooperc. 
Wake up lab computers between 8:15 AM and 4:30 PM on Mondays, Wednesdays, and Fridays for ATDP. This is not meant to be permanent.
> Temporary - Wake up computers during atdp hours

- staff/sys/ldap-lint
Sometimes we give hozers an "owner" like a staffvm, but this causes ldap-lint to complain since they're not in the staffvm range. We should ignore those errors since it's still fine to do this.
> ldap-lint: allow staffvm hozers

- makeservices/makemysql
- makeservices/makemysql-real
Modified makemysql and makemysql-real to automatically update wp db pass if pass is reset
> makeservices: makemysql automatic wp db pass

- staff/lab/economode
Sometimes we take printers out of rotation. Setting economode on
these printers will fail hard (no route to host) and the script ignores 
any printers that are lexicographically after. This adds a check and 
skips over those.
I haven't seen timeout yet but it could plausibly happen so I added
it just in case.
> economode: Skip over transient network/host errors

- acct/check
I'm not sure why this pointed here since in the past it would go to the help page for CalLinkOrganizations, but the query parameters would be thrown away.
> check: use CalLinkOrganizations endpoint

- staff/sys/ocf-kubernetes-deploy
Fixes #145.
This will look for files like `kubernetes/secrets/<secret_name>/*.erb`, and create corresponding Kubernetes secrets containing these files as key-value pairs. This allows us to template files to include injected secrets and then mount the Kubernetes secret resource as a volume into a container.
This allows files like homeserver.yaml in matrix to be stored in the git repo for matrix, and just have the secret portions injected (given the correct volume setup in the deployment yaml).
> ocf-kubernetes-deploy: create k8s secrets from file templates

- staff/puppet/gen-keytab
This TODO was from when we were migrating to puppetserver from the previous puppet master (I added it in https://github.com/jvperrin/utils/commit/26968446d48dcdc4381aad36f7225f53c3065683). However, since this is a symlink to the existing share, it's been fine and I don't think this TODO really makes sense to do any more since we expect this symlink to keep existing.
> gen-keytab: Remove incorrect TODO

- acct/check
This is a follow-up to ocf/etc#108 to update the vhost config paths used by `check` to use the new paths so that we can switch them to be the source of truth and so that we can remove the `~staff` vhost files at some point in the future.
> check: Update vhost config paths (after ocf/etc#108)

- acct/check
We have a number of alumni with calnetUid = 0, which causes us to go over the lookup limit for Berkeley's ldap server
> check: skip over calnetuid 0

- staff/acct/backup-user
We used to have NFS on pandemic, but that is no longer the case as of quite a few years. Let's just warn when running a user backup on `supernova` that it would be faster on the NFS host but not hardcode a hostname here.
> backup-user: Update NFS host warning, not on pandemic now

- acct/check
- makeservices/easywp
- staff/acct/add-to-group
- staff/acct/setup-otp
- staff/acct/sorry/sorry
- staff/acct/sorry/unsorry
- sys/how
I tested `check`, `add-to-group`, and `how`, but have not tested the other scripts apart from testing replacements to make sure they behave the same (`command -v <blah>` vs `which <blah>` for instance, or making sure that echo behaves the same with the extra backslash escaping).
> Fix tests with shellcheck on buster

- staff/sys/migrate-vm
The output must have changed because it looks like this now:
```
Verifying disk copied...                                             
Original SHA1 (on remote server): SHA1(/dev/vg/dev-anthrax)= fccaeceb22bbb3b4939bbd0dbd74268f47f3eb56
New SHA1 (on this server): SHA1(/dev/vg/dev-anthrax)= a97db72f3c1653e538567b00431b3060f57d5e40          
Traceback (most recent call last):                                                     
File "/opt/share/utils/sbin/migrate-vm", line 223, in <module>                            
main()                              
File "/opt/share/utils/sbin/migrate-vm", line 216, in main    
verify_disks(src_lvpath, dest_lvpath)
File "/opt/share/utils/sbin/migrate-vm", line 114, in verify_disks
if p.match(original).group(1) != p.match(copied).group(1):  
```
This …
> Update regex for matching disk names for migrate-vm

- staff/lab/mod-printer
Fix for #101 with regards to https://github.com/ocf/ocfweb/pull/754.
> Printer rotation command

- staff/lab/mod-printer
Using `required=True` is an invalid argument with Python 3.5 (as on `whiteout`). Thus this is the older version which fixes that issue. See #174 for more details about `mod-printer`.
> Replace required flag for mod-printer

- sbin/mod-printer
Add symlink for `mod-printer` into `sbin`. See #174 for more details.
> Add mod-printer symlink

- staff/lab/mod-printer
As it turns out if you run `lpstat` on whiteout it gives you more information about the non-shared printers (for example, `logjam-single` instead of just `single`). Thus this is a re-write of the `mod-printer` script which makes fewer assumptions and implements an actual parsed status/list command.
Also I tested it extensively on `whiteout` from in the lab like the typical use case. The symlinks should still be ok from #176.
> Redo mod-printer with additional whiteout lpstat info

- sys/how
Dash does not understand `command -v` with multiple parameters, which is causing the `how` command to fail with the output
```
/opt/share/utils/bin/how: 63: /opt/share/utils/bin/how: -en: not found
```
because it tries to execute `$(command -v greadlink readlink) -en ...` but `command` isn't outputting anything.
Furthermore, converting this script to a bash script makes it more consistent with how other OCF shell scripts work.
> how: use bash
