- staff/acct/signat
Waiting on a pull request in ocflib and needs python-tabulate to be installed, but it works nicely in a virtualenv.
> Rewrite signat with ocflib

- staff/acct/signat
Handles some weird cases which just came up. Also now shows OCF accounts for student groups.
> Improvements to signat

- acct/check
- makeservices/makemysql
- makeservices/makemysql-real
- staff/acct/sorry/sorry
Sorry this diff is kind of noisy. I made some changes to follow ocflib conventions and wound up making several unimportant line changes as well.
> Kill /opt/ocf and slightly update makemysql

- makeservices/makehttp
I'm pretty surprised this wasn't already done. Maybe I should have assigned it to someone else.
> Rewrite makehttp in python

- net/pyrc
- staff/acct/note
- staff/sys/apt-dated
- staff/web/bludgeon
@matthew-mcallister merging into master for testing
> python2 -> python3 migration

- staff/web/bludgeon
reverting to python2 for the time being since there were issues with python3, also adding -h functionality that renders comment that describes script
@jvperrin
> Revert to Python2 and Help Enhancement

- staff/acct/calnet-breakdowns
- staff/acct/signat
- staff/sys/ldap-lint
See https://github.com/ocf/ocflib/pull/38.
> Fix compatibility with ldap3 version 2

- staff/lab/ocf-tv
now you can do 
$ ocf-tv volume
35%
$ ocf-tv volume +30
65%
$ ocf-tv volume -20
45%
$ ocf-tv mute
/
> volume control +/-, report and mute

- acct/check
is useful when confirming group accounts
> list signatories for group accounts

- requirements-dev.txt
This PR is also to test if PRs actually get run by Jenkins now or not.
> Add dnspython to dev requirements

- staff/sys/stdin2syslog
Now that we're on stretch and this works
> stdin2syslog: directly exec logger

- staff/meetings/meetings.py
We recently removed the regulation requiring people to attend BoD 4 times before joining, in light of the split between BoD and staff meetings. This patch updates the minutes taker to behave accordingly.
> Update meetings script in light of recent BoD eligibility changes

- staff/sys/firewall
Apparently the firewall isn't giving a complete cert chain, so...
> firewall: rip new certificate

- staff/lab/ocf-tv
also slightly better argparse and reorganize the script a bit
+1 to @matthew-mcallister for https://github.com/ocf/puppet/pull/195 for which this is the counterpart.
> update ocf-tv to work without avahi

- .pre-commit-config.yaml
- Makefile
- staff/acct/calnet-breakdowns
- staff/acct/guess-passwords
- staff/acct/note
- staff/lab/economode
- staff/lab/ocf-tv
- staff/meetings/bod
- staff/meetings/minutes
- staff/sys/apt-dater-ocf
- staff/sys/ldap-lint
- staff/sys/ssh-list
Some stuff in `ocf-tv` fails the checks too, but I don't want to mess with #64, so I'll leave that for now.
> Bump pre-commit hooks

- acct/check
- acct/check-dns
- bin/check-dns
- bin/update-symlinks
- update-symlinks
shellcheck cannot be appeased at my current level of experience in writing portable shell scripts
please provide feedback on anything that could be done better in this, if possible.
+= checking for mail vhosts
> check: show dns for primary vhost

- staff/web/bludgeon
(Hopefully) the encoding issues are addressed this time
> bludgeon: convert to python 3

- requirements-dev.txt
- sbin/timecard
- staff/lab/timecard
I updated the [timecard script](https://github.com/ocf/labstats/blob/master/labstats/stats/timecard.py) from labstats, and @jvperrin mentioned it could go here.
> Add updated timecard script

- acct/check-dns
This behavior is mildly surprising and clutters output.
> check-dns: Don't show A/AAAA/MX if there's a CNAME

- acct/check
Dependent on https://github.com/ocf/puppet/pull/401
> check: modify to use privileged UCB ldap bind

- sbin/ocf-kubernetes-deploy
- staff/sys/ocf-kubernetes-deploy
This lets us run the deploy script in a much nicer way. It can be called from Jenkins and makes it easier for the script to be run manually.
> Add ocf-kubernetes-deploy script

- staff/acct/add-to-group
doing `kinit abizer/admin ldapvi cn=ocfhpc` or whatever isn't hard, but this is slightly nicer
> a small script to add users to ldap groups

- makeservices/makemysql-real
See https://docs.python.org/3/library/configparser.html#configparser.ConfigParser.readfp
> makemysql: use read instead of deprecated readfp

- staff/lab/lab-wakeup
This reverts commit ba20603bca962181ebb0e8c27e403be7e9a323de.
> Revert "Temporary - Wake up computers during atdp hours"

- staff/acct/sorry/unsorry
> unsorry: set home directory permissions to 700

- staff/acct/sorry/wpcompromise
This is the most common form of user compromise, so it makes sense to have a .sorry file for it that's more descriptive than phpcompromise.
> add .sorry file for WP compromise

- sbin/add-to-group
- sbin/setup-otp
- staff/acct/setup-otp
see ocf/puppet#682 and ocf/puppet#683
> add setup-otp for configuring OTP secrets on lightning

- staff/acct/sorry/hibp
One part of https://github.com/ocf/projects/issues/39, accounts can be automatically sorried if their password is bad.
> add hibp breach sorry message

- staff/acct/sorry/sorry
- staff/acct/sorry/unsorry
Might be more that needs to be changed. I searched for `a-z` and changed the ones that are obvious.
> Allow numbers in usernames

- staff/lab/economode
I updated the firmware on the printers.
> Support HP FutureSmart 4

- printing/paper
you can just run "paper" now. you wont have to use flags/arguements if you dont want to. also made the "user" arguement optional with "--user" or "-u"
> use prompts to set values for non-inputted arguments

- printing/paper
> fix: make --user optional and include refund/view prompt
